### PR TITLE
add vue syntax support, fix #112

### LINKED ISSUE #112: .vue Files
Please add the .vue extension. That would be great :)

http://vuejs.org/guide/application.html

### PR DESCRIPTION
**Pull request by djyde**

### CODE REVIEW

**Comment by djyde** [comment]
fix #112

**Comment by Mkuhneu** [comment]
thanks +1

**Comment by thelinuxlich** [comment]
How do I enable this?

**Comment by djyde** [comment]
@thelinuxlich No need to enable it manually. If it didn't work, it may be not submitted this patch to package central.

**Comment by thelinuxlich** [comment]
I cloned this repository and it's not enabling the lint on vue files

**Comment by djyde** [comment]
Have you installed SublimeLinter?

**Comment by thelinuxlich** [comment]
of course

**Comment by thelinuxlich** [comment]
It works on .js files

**Comment by xsbear** [comment]
It not works on .vue files, I'v checked the pr code already in the ST packges

**Comment by roadhump** [comment]
@djyde I've just checked, plugin really does not work on vue for me. First, syntax should be `vue`, not `Vue Component` (the name of this file, I suppose https://github.com/vuejs/vue-syntax-highlight/blob/master/vue.tmLanguage). Probably you use different syntax in your ST? Also, I wonder if it is possible to make plugin to correct extract js from `script` tags from files except `html` syntax. As I know, SublimeLinter patches `html` syntax of ST to make it works, but in `vue` files I see this:

**Comment by djyde** [comment]
@roadhump thanks for detail feedback. I'm fixing now.

**Comment by djyde** [comment]
I'd tried reinstall `Vue Syntax Highlight` and `Sublime-linter-contrib-eslint`. It works fine. 😂

**Comment by djyde** [comment]
@roadhump I think `.eslintrc` file did not exist under your folder

**Comment by Coffcer** [comment]
@djyde maybe the issue same as https://github.com/SublimeLinter/SublimeLinter3/issues/356 ,
can you tell us version of your sublimeLinter and sublime ?

**Comment by cornerCao** [comment]
👍

**Comment by cornerCao** [comment]
that's really great 😄

**Pull request merged**
